# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_registrar_prenda.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1045, 676)
        MainWindow.setStyleSheet("background-color: rgb(255, 170, 255);\n"
"font: 16pt \"MV Boli\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, -20, 471, 141))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.entrada_color_prenda = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_color_prenda.setGeometry(QtCore.QRect(210, 160, 181, 31))
        self.entrada_color_prenda.setText("")
        self.entrada_color_prenda.setObjectName("entrada_color_prenda")
        self.entrada_talla_prenda = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_talla_prenda.setGeometry(QtCore.QRect(210, 110, 181, 31))
        self.entrada_talla_prenda.setObjectName("entrada_talla_prenda")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(90, 130, 91, 81))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.boton_registrar_prenda = QtWidgets.QPushButton(self.centralwidget)
        self.boton_registrar_prenda.setGeometry(QtCore.QRect(80, 540, 311, 61))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.boton_registrar_prenda.setFont(font)
        self.boton_registrar_prenda.setObjectName("boton_registrar_prenda")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(90, 180, 91, 81))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.entrada_marca_prenda = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_marca_prenda.setGeometry(QtCore.QRect(210, 210, 181, 31))
        self.entrada_marca_prenda.setText("")
        self.entrada_marca_prenda.setObjectName("entrada_marca_prenda")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(90, 80, 101, 81))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.entrada_tipo_prenda = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_tipo_prenda.setGeometry(QtCore.QRect(210, 270, 181, 31))
        self.entrada_tipo_prenda.setText("")
        self.entrada_tipo_prenda.setObjectName("entrada_tipo_prenda")
        self.entrada_precio_prenda = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_precio_prenda.setGeometry(QtCore.QRect(210, 320, 181, 31))
        self.entrada_precio_prenda.setText("")
        self.entrada_precio_prenda.setObjectName("entrada_precio_prenda")
        self.label_tienda = QtWidgets.QLabel(self.centralwidget)
        self.label_tienda.setGeometry(QtCore.QRect(580, 360, 101, 71))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_tienda.setFont(font)
        self.label_tienda.setObjectName("label_tienda")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(90, 240, 91, 81))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.checkBox_online = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_online.setGeometry(QtCore.QRect(650, 280, 221, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox_online.setFont(font)
        self.checkBox_online.setObjectName("checkBox_online")
        self.combo_temporada = QtWidgets.QComboBox(self.centralwidget)
        self.combo_temporada.setGeometry(QtCore.QRect(200, 390, 221, 41))
        self.combo_temporada.setObjectName("combo_temporada")
        self.combo_temporada.addItem("")
        self.combo_temporada.addItem("")
        self.radio_internacional = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_internacional.setGeometry(QtCore.QRect(780, 160, 191, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.radio_internacional.setFont(font)
        self.radio_internacional.setObjectName("radio_internacional")
        self.radio_peninsula = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_peninsula.setGeometry(QtCore.QRect(780, 70, 281, 21))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.radio_peninsula.setFont(font)
        self.radio_peninsula.setChecked(True)
        self.radio_peninsula.setObjectName("radio_peninsula")
        self.radio_islas = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_islas.setGeometry(QtCore.QRect(780, 110, 181, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.radio_islas.setFont(font)
        self.radio_islas.setObjectName("radio_islas")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(630, 100, 141, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, 380, 151, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_error_talla = QtWidgets.QLabel(self.centralwidget)
        self.label_error_talla.setGeometry(QtCore.QRect(410, 105, 191, 41))
        self.label_error_talla.setText("")
        self.label_error_talla.setObjectName("label_error_talla")
        self.label_error_color = QtWidgets.QLabel(self.centralwidget)
        self.label_error_color.setGeometry(QtCore.QRect(410, 165, 181, 31))
        self.label_error_color.setText("")
        self.label_error_color.setObjectName("label_error_color")
        self.label_error_marca = QtWidgets.QLabel(self.centralwidget)
        self.label_error_marca.setGeometry(QtCore.QRect(410, 210, 161, 31))
        self.label_error_marca.setText("")
        self.label_error_marca.setObjectName("label_error_marca")
        self.label_error_tipo = QtWidgets.QLabel(self.centralwidget)
        self.label_error_tipo.setGeometry(QtCore.QRect(410, 270, 191, 31))
        self.label_error_tipo.setText("")
        self.label_error_tipo.setObjectName("label_error_tipo")
        self.boton_seleccionar_imagen = QtWidgets.QPushButton(self.centralwidget)
        self.boton_seleccionar_imagen.setGeometry(QtCore.QRect(720, 380, 281, 41))
        self.boton_seleccionar_imagen.setObjectName("boton_seleccionar_imagen")
        self.label_imagen = QtWidgets.QLabel(self.centralwidget)
        self.label_imagen.setGeometry(QtCore.QRect(574, 465, 401, 141))
        self.label_imagen.setText("")
        self.label_imagen.setObjectName("label_imagen")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(90, 300, 91, 81))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Introduce los datos de las prendas:"))
        self.label_6.setText(_translate("MainWindow", "Color:"))
        self.boton_registrar_prenda.setText(_translate("MainWindow", "REGISTRAR PRENDA"))
        self.label_7.setText(_translate("MainWindow", "Marca:"))
        self.label_5.setText(_translate("MainWindow", "Talla:"))
        self.label_tienda.setText(_translate("MainWindow", "Tienda:"))
        self.label_9.setText(_translate("MainWindow", "Tipo:"))
        self.checkBox_online.setText(_translate("MainWindow", "Online"))
        self.combo_temporada.setItemText(0, _translate("MainWindow", "Invierno"))
        self.combo_temporada.setItemText(1, _translate("MainWindow", "Verano"))
        self.radio_internacional.setText(_translate("MainWindow", "Internacional"))
        self.radio_peninsula.setText(_translate("MainWindow", "Peninsula"))
        self.radio_islas.setText(_translate("MainWindow", "Islas"))
        self.label_11.setText(_translate("MainWindow", "Destino:"))
        self.label_12.setText(_translate("MainWindow", "Temporada:"))
        self.boton_seleccionar_imagen.setText(_translate("MainWindow", "Seleccionar Archivo"))
        self.label_10.setText(_translate("MainWindow", "Precio:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
